In [1]:
import pandas as pd

In [2]:
# this is a dataframe consisting of a curated list of 485 cells with all or most of the cell body in the volume
# some of the cell subtypes assignments may be erroneous
# this file was created by an inner merge of:
    # "soma_valence_v185.csv"
    # and "220309_cell_type_classification.csv"
    # both original csv files are available here: https://www.microns-explorer.org/phase1

In [3]:
# Note that the following vascular and enthelial cells have one cellid for multiple cells in the volume
# 50 cells sharing the same cellid of 648518346349526102: (1 OPC-pericyte type, 1 pericyte, 48 endothelial)
# 4 endothelial cells sharing the same cellid of 648518346348121670
# 4 endothelial cells sharing the same cellid of 648518346349375478
# 2 endothelial cells sharing the same cellid of 648518346348189552
# all other cells in this dataframe have one unique cellid per cell

In [4]:
celltypelookup = pd.read_csv("data/layer23_celltype_lookup.csv")

In [5]:
celltypelookup

,cell_segid,centroid_x,centroid_y,centroid_z,cell_type_x,cell_subtype,id,cell_type_y,pt_position,soma_x_nm,soma_y_nm,soma_z_nm
0,648518346349538237,41760,60256,1702,pyramidal,pyramidal cell,289,e,[42065 60352 1724],168260,168260,1682600
1,648518346349536816,98128,39856,218,pyramidal,pyramidal cell,281,e,[98028 39919 232],392112,392112,3921120
2,648518346349539797,51248,50608,86,pyramidal,pyramidal cell,283,e,[51691 50574 126],206764,206764,2067640
3,648518346349536851,104928,72496,1448,pyramidal,pyramidal cell,236,e,[104870 72471 1446],419480,419480,4194800
4,648518346349522862,58128,35616,2059,pyramidal,pyramidal cell,202,e,[58210 35590 2059],232840,232840,2328400
...,...,...,...,...,...,...,...,...,...,...,...,...
480,648518346349530569,59680,69104,2113,glia,astrocyte,413,g,[59596 69165 2132],238384,238384,2383840
481,648518346349536717,72704,55888,576,glia,microglia (merged with nucleus of astrocyte 64...,418,g,[72779 55950 577],291116,291116,2911160
482,648518346349536717,72704,55888,576,glia,microglia (merged with nucleus of astrocyte 64...,420,g,[72565 54543 492],290260,290260,2902600
483,648518346349538793,100576,42592,739,glia,OPC,373,g,[100487 42666 727],401948,401948,4019480
484,648518346349525488,78624,74816,1746,glia,oligodendrocyte,412,g,[78612 74702 1749],314448,314448,3144480

In [6]:
# enter a cell id of interest
# e.g., use the copy function in neuroglancer in the cell segmentation panel

lookup = 648518346349514298

In [7]:
query = celltypelookup["cell_segid"] == lookup
querydf = celltypelookup.loc[query, ["cell_segid", "cell_type_x", "cell_subtype"]]
querydf

             cell_segid cell_type_x cell_subtype
402  648518346349514298        glia          OPC

In [8]:
querydf["cell_segid"].to_list()

[648518346349514298]